### ISSUE TITLE
ruby_dep error probably due to not specifying jekyll gem version

### ISSUE THREAD

**Issue by chriswhong** [inket/dokku-buildpack-jekyll3-nginx#12]
Hi, we are currently experiencing this with our buildpack that was based on yours, but after trying yours we see the same issue.  When it tries to install the jekyll gem, it gets a warning about `ruby_dep` saying it can't install on ruby 2.2.1 . 

Any ideas?  Thanks!

```  
     Jekyll not found!
-----> Installing Jekyll
       Successfully installed liquid-4.0.0
       1 gem installed
remote: ERROR:  Error installing jekyll:
remote: 	ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
       Successfully installed safe_yaml-1.0.4
       Successfully installed rouge-2.2.1
       Successfully installed forwardable-extended-2.6.0
       Successfully installed pathutil-0.16.0
       Successfully installed mercenary-0.3.6
       Successfully installed kramdown-1.16.2
       Building native extensions.  This could take a while...
       Successfully installed redcarpet-3.4.0
       Building native extensions.  This could take a while...
       Successfully installed ffi-1.9.18
       Successfully installed rb-inotify-0.9.10
       Successfully installed rb-fsevent-0.10.2
       Successfully installed sass-listen-4.0.0
       Successfully installed sass-3.5.3
       6 gems installed
```

**Comment by inket** [comment]
Hi! Thanks for reporting this. It turns out `ruby_dep` is a dependency of `listen` which is a dependency of `jekyll-watch` and that just got updated to remove the version lock on `listen`.

To solve I will just specify the `listen` version to install.

**Comment by chriswhong** [comment]
Thanks, we spent hours on this and then decided to just build locally and deploy the built site to dokku with a `.static` to get our site back up.  We'll try this fix.  I knew there was some way to quickly change a dependency declaration but don't have enough experience with ruby to know where to do it.
