### ISSUE TITLE
Serving index.htm and index.xml files

### ISSUE THREAD

**Issue by khanlou** [inket/dokku-buildpack-jekyll3-nginx#15]
I know this repo hasn't been updated in a while, but would you open to adding `index.htm` and `index.xml` files to the index directive of the erb template?

Change from

    index index.html;

to

    index index.html index.htm index.xml;

My jekyll site serves the xml feed at `$SITE/feed` and so it doesn't know to serve index.xml as the index of that directory.

Happy to open a PR if you're open to it.

**Comment by inket** [comment]
Sounds good! Please make a PR.
