### ISSUE TITLE
Gemfile not evaluated

### ISSUE THREAD

**Issue by MSchmidt** [inket/dokku-buildpack-jekyll3-nginx#4]
This buildpack uses predefined gems rather than gems defined in a Gemfile. Jekyll supports the Gemfile as a location to define jekyll-plugins. Would it be possible to run bundle install just like the regular ruby buildpack does?

**Comment by inket** [comment]
Would this solve the issue? https://github.com/inket/dokku-buildpack-jekyll3-nginx/pull/5

**Comment by MSchmidt** [comment]
Brilliant! Just ran it and works like a charm. Not a big deal, but since I have jekyll itself in my Gemfile it installed jekyll twice.

**Comment by inket** [comment]
Sweet. Merging it. 👍
